### PR TITLE
Create RKI_COVID19_2020-04-18.csv

### PR DESCRIPTION
**Pull request by MikeJayDee**
I happened to have the 18 April file downloaded that was missing from your dataset. None of the other missing ones unfortunately.

This is my first time working with GitHub so I hope this pull request does what I think it does!

### CODE REVIEW

**Comment by CharlesStr** [comment]
Hello MikeJayDee ,
I have looked at the file (RKI_COVID19_2020-04-18.csv) Where did you get this file from?
Greetings
Charles

**Comment by MikeJayDee** [comment]
I downloaded it from the RKI website on 18 April and it was still in my download folder. You asked for contributions so I checked whether I had downloaded any missing files. (Edit: I renamed it to match your naming rule.)

**Comment by CharlesStr** [comment]
Very well, I will release the data soon. Thanks for your help.

**Comment by CharlesStr** [comment]
Your pull request is in order. Now I just have to import the data into my database. Then I make the merge pull request.

**Comment by CharlesStr** [comment]
thank you for upload

**Pull request closed without merging**
